### PR TITLE
add protocol tags for databases

### PR DESCRIPTION
**Pull request by justinbastress**
re: https://censysio.atlassian.net/browse/CEN-381 -- add the database types to protocols.py.

### CODE REVIEW

**Comment by justinbastress** [comment]
Closed pending update for `devices/*`

**Comment by justinbastress** [comment]
@dadrian did I catch everything that needs to be done for proper tagging?

**Comment by andrewsardone** [comment]
@justinbastress: does this also add a `database` tag for `anyof({oracle, mssql, mysql, postgres})`?

**Comment by justinbastress** [comment]
No, but that should be pretty trivial to add.

**Comment by andrewsardone** [comment]
>> does this also add a `database` tag 
>
> No, but that should be pretty trivial to add.

💥 https://github.com/zmap/ztag/pull/112 ✨

**Pull request merged**
